import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/assets/css/globals.css";
import Providers from "@/store/Provider";
import ClientWrapper from "@/components/clientWrapper";

const poppins = Poppins({
  variable: "--Poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Expensive Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased    `}>
        <Providers>
          <ClientWrapper>{children}</ClientWrapper>
        </Providers>
      </body>
    </html>
  );
}
